name: C/C++ CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  ubuntu_18:
    name: Ubuntu 18
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: install packages
      run: sudo apt-get update && sudo apt-get install -y zlib1g-dev gcc
    - name: build
      run:  make
    - name: test
      run: make test
  os_x_10:
    name: OSX 10
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: make
    - name: test
      run: make test
